# Minimal config. version is the only required field.
version = 1

[merge.automerge_dependencies]
# automerge by upgrade version for pull requests authored by dependabot or renovate.
usernames = ["dependabot"]
