# Minimal config. version is the only required field.
version = 1

[merge.automerge_dependencies]
usernames = ["dependabot", "renovate"]

[update]
always = true

merge.notify_on_conflict = false
merge.method = "squash"
