name: Audit
on:
  workflow_call:

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.3
      - uses: xmc-rs/audit-check@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
