name: Update

on:
  workflow_call:
    inputs:
      svd_file:
        required: true
        type: string

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Install svd2rust
        uses: xmc-rs/cargo@v1.0.0
        with:
          command: install
          args: svd2rust
      - name: Install Form
        uses: xmc-rs/cargo@v1.0.0
        with:
          command: install
          args: form
      - uses: oleksiyrudenko/gha-git-credentials@v2.1.2
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Generate Code from SVD
        run: |
          rm -r src/
          svd2rust -i ${{ inputs.svd_file }}
          mkdir src
          form -i lib.rs -o src/
          cargo fmt
          rm lib.rs
      - uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_SECRET_KEY }}
      - uses: peter-evans/create-pull-request@v6.1.0
        with:
          branch: svd-update
          commit-message: "feat: updating from newer svd2rust"
          title: "feat: updating from newer svd2rust"
          labels: automerge
          token: ${{ steps.generate-token.outputs.token }}
